version: "3.9"

services:
  mongoPoke:
    image: mongo:4
    volumes:
      - mongo-data:/data/db

  poke_back:
    image: node:18-alpine3.16
    volumes:
      - ./:/app
    working_dir: /app
    command: npm run dev
    environment:
      - MONGO_INITDB_ROOT_USERNAME=fede
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 3000:3000
    networks:
      - pokeRed
      - default

volumes:
  mongo-data:

networks:
  pokeRed:
    name: pokeRed
